---
apiVersion: v1
kind: Service
metadata:
  name: metrics-demo
  namespace: metrics-demo
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: metrics-demo


